Docker compose cron (#123)
* ms-cron
disable bull - delay error
ioredis/built/redis/event_handler.js:177
                    self.flushQueue(new errors_1.MaxRetriesPerRequestError(maxRetriesPerRequest));
                                    ^
MaxRetriesPerRequestError: Reached the max retries per request limit (which is 20). Refer to "maxRetriesPerRequest" option for details.

* docs

* ms-cron: nestjs-cron

* *

* yarn add package

* docker-compose-cron.yml

* clickhouse docker connect

* tsconfig